import 'package:flutter/material.dart';

final List<Map<String, dynamic>> stampIconsMap = [
  
  //Simbolos
  {'type': 'icon', 'icon': IconData(0xe236, fontFamily: 'MaterialIcons'), 'label': 'Equalizer'},
  {'type': 'icon', 'icon': IconData(0xf04fa, fontFamily: 'MaterialIcons'), 'label': 'Emergency'},
  {'type': 'icon', 'icon': IconData(0xe261, fontFamily: 'MaterialIcons'), 'label': 'Female'},
  {'type': 'icon', 'icon': IconData(0xe1eb, fontFamily: 'MaterialIcons'), 'label': 'Dnd Forwardslash'},
  {'type': 'icon', 'icon': IconData(0xefd7, fontFamily: 'MaterialIcons'), 'label': 'Do Disturb On Outlined'},
  {'type': 'icon', 'icon': IconData(0xe1f6, fontFamily: 'MaterialIcons'), 'label': 'Done'},
  {'type': 'icon', 'icon': IconData(0xe1f7, fontFamily: 'MaterialIcons'), 'label': 'Done All'},
  {'type': 'icon', 'icon': IconData(0xe1f8, fontFamily: 'MaterialIcons'), 'label': 'Done Outline'},
  {'type': 'icon', 'icon': IconData(0xe1af, fontFamily: 'MaterialIcons'), 'label': 'Dangerous'},
  {'type': 'icon', 'icon': IconData(0xe168, fontFamily: 'MaterialIcons'), 'label': 'Clear'},
  {'type': 'icon', 'icon': IconData(0xe0e1, fontFamily: 'MaterialIcons'), 'label': 'Block'},
  {'type': 'icon', 'icon': IconData(0xe0e4, fontFamily: 'MaterialIcons'), 'label': 'Bluetooth'},
  {'type': 'icon', 'icon': IconData(0xe0f1, fontFamily: 'MaterialIcons'), 'label': 'Bookmark'},
  {'type': 'icon', 'icon': IconData(0xe114, fontFamily: 'MaterialIcons'), 'label': 'Bubble Chart'},
  {'type': 'icon', 'icon': IconData(0xe12f, fontFamily: 'MaterialIcons'), 'label': 'Camera'},
  {'type': 'icon', 'icon': IconData(0xf04ca, fontFamily: 'MaterialIcons'), 'label': 'Candlestick Chart'},
  {'type': 'icon', 'icon': IconData(0xe138, fontFamily: 'MaterialIcons'), 'label': 'Campaign'},
  {'type': 'icon', 'icon': IconData(0xe0b2, fontFamily: 'MaterialIcons'), 'label': 'Attach Money'},
  {'type': 'icon', 'icon': IconData(0xe0b6, fontFamily: 'MaterialIcons'), 'label': 'Audiotrack'},
  {'type': 'icon', 'icon': IconData(0xf596, fontFamily: 'MaterialIcons'), 'label': 'Auto Awesome Rounded'},
  {'type': 'icon', 'icon': IconData(0xe07e, fontFamily: 'MaterialIcons'), 'label': 'All Inclusive'},
  {'type': 'icon', 'icon': IconData(0xe081, fontFamily: 'MaterialIcons'), 'label': 'Alternate Email'},
  {'type': 'icon', 'icon': IconData(0xe3f7, fontFamily: 'MaterialIcons'), 'label': 'Monetization On'},
  {'type': 'icon', 'icon': IconData(0xe415, fontFamily: 'MaterialIcons'), 'label': 'Music Note'},
  {'type': 'icon', 'icon': IconData(0xe3c5, fontFamily: 'MaterialIcons'), 'label': 'Male'},
  {'type': 'icon', 'icon': IconData(0xe3a2, fontFamily: 'MaterialIcons'), 'label': 'Local Police'},
  {'type': 'icon', 'icon': IconData(0xe396, fontFamily: 'MaterialIcons'), 'label': 'Local Hospital'},
  {'type': 'icon', 'icon': IconData(0xe399, fontFamily: 'MaterialIcons'), 'label': 'Local Library'},
  {'type': 'icon', 'icon': IconData(0xe2d0, fontFamily: 'MaterialIcons'), 'label': 'Gamepad'},
  {'type': 'icon', 'icon': IconData(0xe2df, fontFamily: 'MaterialIcons'), 'label': 'Grade'},
  {'type': 'icon', 'icon': IconData(0xf7df, fontFamily: 'MaterialIcons'), 'label': 'Health And Safety Rounded'},
  {'type': 'icon', 'icon': IconData(0xf7fb, fontFamily: 'MaterialIcons'), 'label': 'Hotel Rounded'},
  {'type': 'icon', 'icon': IconData(0xe3f9, fontFamily: 'MaterialIcons'), 'label': 'Money Off'},
  {'type': 'icon', 'icon': IconData(0xe2e3, fontFamily: 'MaterialIcons'), 'label': 'Multitrack Audio'},
  {'type': 'icon', 'icon': IconData(0xe450, fontFamily: 'MaterialIcons'), 'label': 'Notifications Active'},
  {'type': 'icon', 'icon': IconData(0xf0542, fontFamily: 'MaterialIcons'), 'label': 'Numbers'},
  {'type': 'icon', 'icon': IconData(0xe446, fontFamily: 'MaterialIcons'), 'label': 'Not Interested'},
  {'type': 'icon', 'icon': IconData(0xe46a, fontFamily: 'MaterialIcons'), 'label': 'Paid'},
  {'type': 'icon', 'icon': IconData(0xe4be, fontFamily: 'MaterialIcons'), 'label': 'Piano'},
  {'type': 'icon', 'icon': IconData(0xe4c3, fontFamily: 'MaterialIcons'), 'label': 'Pie Chart'},
  {'type': 'icon', 'icon': IconData(0xe4f0, fontFamily: 'MaterialIcons'), 'label': 'Public'},
  {'type': 'icon', 'icon': IconData(0xe4ec, fontFamily: 'MaterialIcons'), 'label': 'Priority High'},
  {'type': 'icon', 'icon': IconData(0xe51c, fontFamily: 'MaterialIcons'), 'label': 'Remove Red Eye'},
  {'type': 'icon', 'icon': IconData(0xe52d, fontFamily: 'MaterialIcons'), 'label': 'Report Problem'},
  {'type': 'icon', 'icon': IconData(0xf055a, fontFamily: 'MaterialIcons'), 'label': 'Recycling'},
  {'type': 'icon', 'icon': IconData(0xe53b, fontFamily: 'MaterialIcons'), 'label': 'Room'},
  {'type': 'icon', 'icon': IconData(0xf056d, fontFamily: 'MaterialIcons'), 'label': 'South America'},
  {'type': 'icon', 'icon': IconData(0xe5c7, fontFamily: 'MaterialIcons'), 'label': 'Smoke Free'},
  {'type': 'icon', 'icon': IconData(0xe5c8, fontFamily: 'MaterialIcons'), 'label': 'Smoking Rooms'},
  {'type': 'icon', 'icon': IconData(0xe57f, fontFamily: 'MaterialIcons'), 'label': 'Settings'},
  {'type': 'icon', 'icon': IconData(0xe569, fontFamily: 'MaterialIcons'), 'label': 'Security'},
  {'type': 'icon', 'icon': IconData(0xe570, fontFamily: 'MaterialIcons'), 'label': 'Sell'},
  {'type': 'icon', 'icon': IconData(0xe654, fontFamily: 'MaterialIcons'), 'label': 'Theater Comedy'},
  {'type': 'icon', 'icon': IconData(0xf47d, fontFamily: 'MaterialIcons'), 'label': 'Verified User Outlined'},
  {'type': 'icon', 'icon': IconData(0xe69a, fontFamily: 'MaterialIcons'), 'label': 'Verified User'},
  {'type': 'icon', 'icon': IconData(0xf47c, fontFamily: 'MaterialIcons'), 'label': 'Verified Outlined'},
  {'type': 'icon', 'icon': IconData(0xe699, fontFamily: 'MaterialIcons'), 'label': 'Verified'},
  {'type': 'icon', 'icon': IconData(0xf06c6, fontFamily: 'MaterialIcons'), 'label': 'Vaping Rooms'},
  {'type': 'icon', 'icon': IconData(0xe685, fontFamily: 'MaterialIcons'), 'label': 'Turned In'},
  {'type': 'icon', 'icon': IconData(0xe682, fontFamily: 'MaterialIcons'), 'label': 'Tty'},
  {'type': 'icon', 'icon': IconData(0xe67b, fontFamily: 'MaterialIcons'), 'label': 'Translate'},
  {'type': 'icon', 'icon': IconData(0xe679, fontFamily: 'MaterialIcons'), 'label': 'Transgender'},
  {'type': 'icon', 'icon': IconData(0xf058e, fontFamily: 'MaterialIcons'), 'label': 'Token'},
  {'type': 'icon', 'icon': IconData(0xf05ae, fontFamily: 'MaterialIcons'), 'label': 'Workspace Premium'},
  {'type': 'icon', 'icon': IconData(0xf05ad, fontFamily: 'MaterialIcons'), 'label': 'Wordpress'},
  {'type': 'icon', 'icon': IconData(0xf05a5, fontFamily: 'MaterialIcons'), 'label': 'Wechat'},

  //Currency
  {'type': 'icon', 'icon': IconData(0xf06bc, fontFamily: 'MaterialIcons'), 'label': 'Currency Bitcoin'},
  {'type': 'icon', 'icon': IconData(0xf04dc, fontFamily: 'MaterialIcons'), 'label': 'Currency Exchange'},
  {'type': 'icon', 'icon': IconData(0xf04dd, fontFamily: 'MaterialIcons'), 'label': 'Currency Franc'},
  {'type': 'icon', 'icon': IconData(0xf04de, fontFamily: 'MaterialIcons'), 'label': 'Currency Lira'},
  {'type': 'icon', 'icon': IconData(0xf04df, fontFamily: 'MaterialIcons'), 'label': 'Currency Pound'},
  {'type': 'icon', 'icon': IconData(0xf04e0, fontFamily: 'MaterialIcons'), 'label': 'Currency Ruble'},
  {'type': 'icon', 'icon': IconData(0xf04e1, fontFamily: 'MaterialIcons'), 'label': 'Currency Rupee'},
  {'type': 'icon', 'icon': IconData(0xf04e2, fontFamily: 'MaterialIcons'), 'label': 'Currency Yen'},
  {'type': 'icon', 'icon': IconData(0xf04e3, fontFamily: 'MaterialIcons'), 'label': 'Currency Yuan'},
  {'type': 'icon', 'icon': IconData(0xe23b, fontFamily: 'MaterialIcons'), 'label': 'Euro'},

  //Veículos
  {'type': 'icon', 'icon': IconData(0xf07a2, fontFamily: 'MaterialIcons'), 'label': 'Fire Truck'},
  {'type': 'icon', 'icon': IconData(0xe1d2, fontFamily: 'MaterialIcons'), 'label': 'Directions Bike'},
  {'type': 'icon', 'icon': IconData(0xe1d3, fontFamily: 'MaterialIcons'), 'label': 'Directions Boat'},
  {'type': 'icon', 'icon': IconData(0xe1d3, fontFamily: 'MaterialIcons'), 'label': 'Directions Boat'},
  {'type': 'icon', 'icon': IconData(0xe1d7, fontFamily: 'MaterialIcons'), 'label': 'Directions Car'},
  {'type': 'icon', 'icon': IconData(0xe1da, fontFamily: 'MaterialIcons'), 'label': 'Directions Railway'},
  {'type': 'icon', 'icon': IconData(0xe54d, fontFamily: 'MaterialIcons'), 'label': 'Sailing'},
  {'type': 'icon', 'icon': IconData(0xf055c, fontFamily: 'MaterialIcons'), 'label': 'Rocket'},
  {'type': 'icon', 'icon': IconData(0xf055d, fontFamily: 'MaterialIcons'), 'label': 'Rocket Launch'},
  {'type': 'icon', 'icon': IconData(0xe65f, fontFamily: 'MaterialIcons'), 'label': 'Time To Leave'},
  {'type': 'icon', 'icon': IconData(0xe672, fontFamily: 'MaterialIcons'), 'label': 'Toys'},
  {'type': 'icon', 'icon': IconData(0xe674, fontFamily: 'MaterialIcons'), 'label': 'Traffic'},
  {'type': 'icon', 'icon': IconData(0xe689, fontFamily: 'MaterialIcons'), 'label': 'Two Wheeler'},
  {'type': 'icon', 'icon': IconData(0xe5ce, fontFamily: 'MaterialIcons'), 'label': 'Snowmobile'},
  {'type': 'icon', 'icon': IconData(0xe54b, fontFamily: 'MaterialIcons'), 'label': 'Rv Hookup'},
  {'type': 'icon', 'icon': IconData(0xe483, fontFamily: 'MaterialIcons'), 'label': 'Pedal Bike'},
  {'type': 'icon', 'icon': IconData(0xe40a, fontFamily: 'MaterialIcons'), 'label': 'Motorcycle'},
  {'type': 'icon', 'icon': IconData(0xf0868, fontFamily: 'MaterialIcons'), 'label': 'Front Loader'},
  {'type': 'icon', 'icon': IconData(0xf0866, fontFamily: 'MaterialIcons'), 'label': 'Forklift'},
  {'type': 'icon', 'icon': IconData(0xe3a6, fontFamily: 'MaterialIcons'), 'label': 'Local Shipping'},
  {'type': 'icon', 'icon': IconData(0xe3a7, fontFamily: 'MaterialIcons'), 'label': 'Local Taxi'},
  {'type': 'icon', 'icon': IconData(0xe400, fontFamily: 'MaterialIcons'), 'label': 'Moped'},
  {'type': 'icon', 'icon': IconData(0xe06e, fontFamily: 'MaterialIcons'), 'label': 'Airplanemode Active'},
  {'type': 'icon', 'icon': IconData(0xe071, fontFamily: 'MaterialIcons'), 'label': 'Airport Shuttle'},
  {'type': 'icon', 'icon': IconData(0xe1bd, fontFamily: 'MaterialIcons'), 'label': 'Delivery Dining'},
  {'type': 'icon', 'icon': IconData(0xe208, fontFamily: 'MaterialIcons'), 'label': 'Drive Eta'},

  //Veículos & Construções
  {'type': 'icon', 'icon': IconData(0xe233, fontFamily: 'MaterialIcons'), 'label': 'Emoji Transportation'},

  //Construções
  {'type': 'icon', 'icon': IconData(0xf04fd, fontFamily: 'MaterialIcons'), 'label': 'Factory'},
  {'type': 'icon', 'icon': IconData(0xe6bc, fontFamily: 'MaterialIcons'), 'label': 'Villa'},
  {'type': 'icon', 'icon': IconData(0xf05a0, fontFamily: 'MaterialIcons'), 'label': 'Warehouse'},
  {'type': 'icon', 'icon': IconData(0xe6d1, fontFamily: 'MaterialIcons'), 'label': 'Water Damage'},
  {'type': 'icon', 'icon': IconData(0xe60a, fontFamily: 'MaterialIcons'), 'label': 'Store'},
  {'type': 'icon', 'icon': IconData(0xe60c, fontFamily: 'MaterialIcons'), 'label': 'Storefront'},
  {'type': 'icon', 'icon': IconData(0xf0572, fontFamily: 'MaterialIcons'), 'label': 'Stadium'},
  {'type': 'icon', 'icon': IconData(0xe53a, fontFamily: 'MaterialIcons'), 'label': 'Roofing'},
  {'type': 'icon', 'icon': IconData(0xe42c, fontFamily: 'MaterialIcons'), 'label': 'Night Shelter'},
  {'type': 'icon', 'icon': IconData(0xe318, fontFamily: 'MaterialIcons'), 'label': 'Home'},
  {'type': 'icon', 'icon': IconData(0xf050e, fontFamily: 'MaterialIcons'), 'label': 'Fort'},
  {'type': 'icon', 'icon': IconData(0xe328, fontFamily: 'MaterialIcons'), 'label': 'House'},
  {'type': 'icon', 'icon': IconData(0xe32a, fontFamily: 'MaterialIcons'), 'label': 'Houseboat'},
  {'type': 'icon', 'icon': IconData(0xe3a8, fontFamily: 'MaterialIcons'), 'label': 'Location City'},
  {'type': 'icon', 'icon': IconData(0xe0b4, fontFamily: 'MaterialIcons'), 'label': 'Attractions'},
  {'type': 'icon', 'icon': IconData(0xe089, fontFamily: 'MaterialIcons'), 'label': 'Apartment'},
  {'type': 'icon', 'icon': IconData(0xf04cb, fontFamily: 'MaterialIcons'), 'label': 'Castle'},
  {'type': 'icon', 'icon': IconData(0xe118, fontFamily: 'MaterialIcons'), 'label': 'Bungalow'},
  {'type': 'icon', 'icon': IconData(0xe263, fontFamily: 'MaterialIcons'), 'label': 'Festival'},

  //Religião
  {'type': 'icon', 'icon': IconData(0xf0588, fontFamily: 'MaterialIcons'), 'label': 'Temple Hindu'},
  {'type': 'icon', 'icon': IconData(0xf0587, fontFamily: 'MaterialIcons'), 'label': 'Temple Buddhist'},
  {'type': 'icon', 'icon': IconData(0xf053e, fontFamily: 'MaterialIcons'), 'label': 'Mosque'},
  {'type': 'icon', 'icon': IconData(0xf04cd, fontFamily: 'MaterialIcons'), 'label': 'Church'},
  {'type': 'icon', 'icon': IconData(0xf0582, fontFamily: 'MaterialIcons'), 'label': 'Synagogue'},

  //Pessoas
  {'type': 'icon', 'icon': IconData(0xe1dc, fontFamily: 'MaterialIcons'), 'label': 'Directions Run'},
  {'type': 'icon', 'icon': IconData(0xf04f9, fontFamily: 'MaterialIcons'), 'label': 'Elderly Woman'},
  {'type': 'icon', 'icon': IconData(0xe231, fontFamily: 'MaterialIcons'), 'label': 'Emoji People'},
  {'type': 'icon', 'icon': IconData(0xe222, fontFamily: 'MaterialIcons'), 'label': 'Elderly'},
  {'type': 'icon', 'icon': IconData(0xe6e4, fontFamily: 'MaterialIcons'), 'label': 'Wheelchair Pickup'},
  {'type': 'icon', 'icon': IconData(0xe257, fontFamily: 'MaterialIcons'), 'label': 'Family Restroom'},
  {'type': 'icon', 'icon': IconData(0xf0538, fontFamily: 'MaterialIcons'), 'label': 'Man'},
  {'type': 'icon', 'icon': IconData(0xf0513, fontFamily: 'MaterialIcons'), 'label': 'Girl'},
  {'type': 'icon', 'icon': IconData(0xe441, fontFamily: 'MaterialIcons'), 'label': 'Nordic Walking'},
  {'type': 'icon', 'icon': IconData(0xe6dc, fontFamily: 'MaterialIcons'), 'label': 'Wc'},
  {'type': 'icon', 'icon': IconData(0xe622, fontFamily: 'MaterialIcons'), 'label': 'Surfing'},
  {'type': 'icon', 'icon': IconData(0xe5cd, fontFamily: 'MaterialIcons'), 'label': 'Snowboarding'},
  {'type': 'icon', 'icon': IconData(0xf06c2, fontFamily: 'MaterialIcons'), 'label': 'Scuba Diving'},
  {'type': 'icon', 'icon': IconData(0xe56f, fontFamily: 'MaterialIcons'), 'label': 'Self Improvement'},
  {'type': 'icon', 'icon': IconData(0xe5bc, fontFamily: 'MaterialIcons'), 'label': 'Skateboarding'},
  {'type': 'icon', 'icon': IconData(0xe5bf, fontFamily: 'MaterialIcons'), 'label': 'Sledding'},
  {'type': 'icon', 'icon': IconData(0xe5cf, fontFamily: 'MaterialIcons'), 'label': 'Snowshoeing'},
  {'type': 'icon', 'icon': IconData(0xe543, fontFamily: 'MaterialIcons'), 'label': 'Rowing'},
  {'type': 'icon', 'icon': IconData(0xe4dc, fontFamily: 'MaterialIcons'), 'label': 'Pool'},
  {'type': 'icon', 'icon': IconData(0xe4e5, fontFamily: 'MaterialIcons'), 'label': 'Pregnant Woman'},
  {'type': 'icon', 'icon': IconData(0xe477, fontFamily: 'MaterialIcons'), 'label': 'Paragliding'},
  {'type': 'icon', 'icon': IconData(0xe313, fontFamily: 'MaterialIcons'), 'label': 'Hiking'},
  {'type': 'icon', 'icon': IconData(0xe2f1, fontFamily: 'MaterialIcons'), 'label': 'Hail'},
  {'type': 'icon', 'icon': IconData(0xe35f, fontFamily: 'MaterialIcons'), 'label': 'Kitesurfing'},
  {'type': 'icon', 'icon': IconData(0xe350, fontFamily: 'MaterialIcons'), 'label': 'Kayaking'},
  {'type': 'icon', 'icon': IconData(0xe41b, fontFamily: 'MaterialIcons'), 'label': 'Nature People'},
  {'type': 'icon', 'icon': IconData(0xf0854, fontFamily: 'MaterialIcons'), 'label': 'Assist Walker'},
  {'type': 'icon', 'icon': IconData(0xf0856, fontFamily: 'MaterialIcons'), 'label': 'Blind'},
  {'type': 'icon', 'icon': IconData(0xe0cf, fontFamily: 'MaterialIcons'), 'label': 'Bathtub'},
  {'type': 'icon', 'icon': IconData(0xf04c8, fontFamily: 'MaterialIcons'), 'label': 'Boy'},
  {'type': 'icon', 'icon': IconData(0xf085c, fontFamily: 'MaterialIcons'), 'label': 'Diversity 3'},
  {'type': 'icon', 'icon': IconData(0xe200, fontFamily: 'MaterialIcons'), 'label': 'Downhill Skiing'},

  //Esportes
  {'type': 'icon', 'icon': IconData(0xe5ea, fontFamily: 'MaterialIcons'), 'label': 'Sports Golf'},
  {'type': 'icon', 'icon': IconData(0xf06c3, fontFamily: 'MaterialIcons'), 'label': 'Sports Gymnastics'},
  {'type': 'icon', 'icon': IconData(0xe5eb, fontFamily: 'MaterialIcons'), 'label': 'Sports Handball'},
  {'type': 'icon', 'icon': IconData(0xe5e7, fontFamily: 'MaterialIcons'), 'label': 'Sports Cricket'},
  {'type': 'icon', 'icon': IconData(0xe5e8, fontFamily: 'MaterialIcons'), 'label': 'Sports Esports'},
  {'type': 'icon', 'icon': IconData(0xe5e9, fontFamily: 'MaterialIcons'), 'label': 'Sports Football'},
  {'type': 'icon', 'icon': IconData(0xe5e3, fontFamily: 'MaterialIcons'), 'label': 'Sports'},
  {'type': 'icon', 'icon': IconData(0xe5e4, fontFamily: 'MaterialIcons'), 'label': 'Sports Bar'},
  {'type': 'icon', 'icon': IconData(0xe5e5, fontFamily: 'MaterialIcons'), 'label': 'Sports Baseball'},
  {'type': 'icon', 'icon': IconData(0xf3d7, fontFamily: 'MaterialIcons'), 'label': 'Sports Volleyball Outlined'},
  {'type': 'icon', 'icon': IconData(0xe5f4, fontFamily: 'MaterialIcons'), 'label': 'Sports Volleyball'},
  {'type': 'icon', 'icon': IconData(0xe5f3, fontFamily: 'MaterialIcons'), 'label': 'Sports Tennis'},
  {'type': 'icon', 'icon': IconData(0xe5f2, fontFamily: 'MaterialIcons'), 'label': 'Sports Soccer'},
  {'type': 'icon', 'icon': IconData(0xe5f1, fontFamily: 'MaterialIcons'), 'label': 'Sports Score'},
  {'type': 'icon', 'icon': IconData(0xe5ef, fontFamily: 'MaterialIcons'), 'label': 'Sports Motorsports'},
  {'type': 'icon', 'icon': IconData(0xe5ee, fontFamily: 'MaterialIcons'), 'label': 'Sports Mma'},
  {'type': 'icon', 'icon': IconData(0xf056f, fontFamily: 'MaterialIcons'), 'label': 'Sports Martial Arts'},
  {'type': 'icon', 'icon': IconData(0xe5ed, fontFamily: 'MaterialIcons'), 'label': 'Sports Kabaddi'},
  {'type': 'icon', 'icon': IconData(0xe5ec, fontFamily: 'MaterialIcons'), 'label': 'Sports Hockey'},
  {'type': 'icon', 'icon': IconData(0xe2d8, fontFamily: 'MaterialIcons'), 'label': 'Golf Course'},

  //Natureza
  {'type': 'icon', 'icon': IconData(0xf07d3, fontFamily: 'MaterialIcons'), 'label': 'Volcano'},
  {'type': 'icon', 'icon': IconData(0xf0797, fontFamily: 'MaterialIcons'), 'label': 'Cyclone'},
  {'type': 'icon', 'icon': IconData(0xf071b, fontFamily: 'MaterialIcons'), 'label': 'Thunderstorm Outlined'},
  {'type': 'icon', 'icon': IconData(0xf07cb, fontFamily: 'MaterialIcons'), 'label': 'Thunderstorm'},
  {'type': 'icon', 'icon': IconData(0xe1b0, fontFamily: 'MaterialIcons'), 'label': 'Dark Mode'},
  {'type': 'icon', 'icon': IconData(0xe6d0, fontFamily: 'MaterialIcons'), 'label': 'Water'},
  {'type': 'icon', 'icon': IconData(0xf0575, fontFamily: 'MaterialIcons'), 'label': 'Sunny'},
  {'type': 'icon', 'icon': IconData(0xe6da, fontFamily: 'MaterialIcons'), 'label': 'Wb Twighlight'},
  {'type': 'icon', 'icon': IconData(0xe6e3, fontFamily: 'MaterialIcons'), 'label': 'Whatshot'},
  {'type': 'icon', 'icon': IconData(0xf07cf, fontFamily: 'MaterialIcons'), 'label': 'Tsunami'},
  {'type': 'icon', 'icon': IconData(0xe648, fontFamily: 'MaterialIcons'), 'label': 'Terrain'},
  {'type': 'icon', 'icon': IconData(0xe478, fontFamily: 'MaterialIcons'), 'label': 'Park'},
  {'type': 'icon', 'icon': IconData(0xe41a, fontFamily: 'MaterialIcons'), 'label': 'Nature'},
  {'type': 'icon', 'icon': IconData(0xe430, fontFamily: 'MaterialIcons'), 'label': 'Nights Stay'},
  {'type': 'icon', 'icon': IconData(0xe4a0, fontFamily: 'MaterialIcons'), 'label': 'Pest Control Rodent'},
  {'type': 'icon', 'icon': IconData(0xe4a1, fontFamily: 'MaterialIcons'), 'label': 'Pets'},
  {'type': 'icon', 'icon': IconData(0xe5d8, fontFamily: 'MaterialIcons'), 'label': 'Spa'},
  {'type': 'icon', 'icon': IconData(0xe2e4, fontFamily: 'MaterialIcons'), 'label': 'Grass'},
  {'type': 'icon', 'icon': IconData(0xf050a, fontFamily: 'MaterialIcons'), 'label': 'Forest'},
  {'type': 'icon', 'icon': IconData(0xe393, fontFamily: 'MaterialIcons'), 'label': 'Local Florist'},
  {'type': 'icon', 'icon': IconData(0xf17b, fontFamily: 'MaterialIcons'), 'label': 'Local Florist Outlined'},
  {'type': 'icon', 'icon': IconData(0xe392, fontFamily: 'MaterialIcons'), 'label': 'Local Fire Department'},
  {'type': 'icon', 'icon': IconData(0xe37a, fontFamily: 'MaterialIcons'), 'label': 'Light Mode'},
  {'type': 'icon', 'icon': IconData(0xe0db, fontFamily: 'MaterialIcons'), 'label': 'Bedtime'},
  {'type': 'icon', 'icon': IconData(0xe115, fontFamily: 'MaterialIcons'), 'label': 'Bug Report'},
  {'type': 'icon', 'icon': IconData(0xe106, fontFamily: 'MaterialIcons'), 'label': 'Brightness 2'},
  {'type': 'icon', 'icon': IconData(0xf04da, fontFamily: 'MaterialIcons'), 'label': 'Cruelty Free'},
  {'type': 'icon', 'icon': IconData(0xe217, fontFamily: 'MaterialIcons'), 'label': 'Eco'},

  //Natureza & Energia
  {'type': 'icon', 'icon': IconData(0xf07a0, fontFamily: 'MaterialIcons'), 'label': 'Energy Savings Leaf'},

  //Energia
  {'type': 'icon', 'icon': IconData(0xe230, fontFamily: 'MaterialIcons'), 'label': 'Emoji Objects'},
  {'type': 'icon', 'icon': IconData(0xf058d, fontFamily: 'MaterialIcons'), 'label': 'Tips And Updates'},
  {'type': 'icon', 'icon': IconData(0xe684, fontFamily: 'MaterialIcons'), 'label': 'Tungsten'},
  {'type': 'icon', 'icon': IconData(0xe293, fontFamily: 'MaterialIcons'), 'label': 'Flash On'},
  {'type': 'icon', 'icon': IconData(0xf855, fontFamily: 'MaterialIcons'), 'label': 'Lightbulb Rounded'},
  {'type': 'icon', 'icon': IconData(0xe37b, fontFamily: 'MaterialIcons'), 'label': 'Lightbulb'},
  {'type': 'icon', 'icon': IconData(0xe0ee, fontFamily: 'MaterialIcons'), 'label': 'Bolt'},
  {'type': 'icon', 'icon': IconData(0xf079c, fontFamily: 'MaterialIcons'), 'label': 'Electric Bolt'},

  //Gestos com as Mãos
  {'type': 'icon', 'icon': IconData(0xe65b, fontFamily: 'MaterialIcons'), 'label': 'Thumb Up'},
  {'type': 'icon', 'icon': IconData(0xe658, fontFamily: 'MaterialIcons'), 'label': 'Thumb Down'},
  {'type': 'icon', 'icon': IconData(0xe6c6, fontFamily: 'MaterialIcons'), 'label': 'Volunteer Activism'},
  {'type': 'icon', 'icon': IconData(0xe6cd, fontFamily: 'MaterialIcons'), 'label': 'Wash'},
  {'type': 'icon', 'icon': IconData(0xe5d0, fontFamily: 'MaterialIcons'), 'label': 'Soap'},
  {'type': 'icon', 'icon': IconData(0xe50f, fontFamily: 'MaterialIcons'), 'label': 'Recommend'},
  {'type': 'icon', 'icon': IconData(0xe50b, fontFamily: 'MaterialIcons'), 'label': 'Real Estate Agent'},
  {'type': 'icon', 'icon': IconData(0xf2f2, fontFamily: 'MaterialIcons'), 'label': 'Recommend Outlined'},
  {'type': 'icon', 'icon': IconData(0xf0544, fontFamily: 'MaterialIcons'), 'label': 'Pan Tool Alt'},
  {'type': 'icon', 'icon': IconData(0xf0510, fontFamily: 'MaterialIcons'), 'label': 'Front Hand'},
  {'type': 'icon', 'icon': IconData(0xf04c5, fontFamily: 'MaterialIcons'), 'label': 'Back Hand'},

  //Rostos
  {'type': 'icon', 'icon': IconData(0xe57b, fontFamily: 'MaterialIcons'), 'label': 'Sentiment Satisfied Alt'},
  {'type': 'icon', 'icon': IconData(0xe578, fontFamily: 'MaterialIcons'), 'label': 'Sentiment Dissatisfied'},
  {'type': 'icon', 'icon': IconData(0xf35f, fontFamily: 'MaterialIcons'), 'label': 'Sentiment Very Dissatisfied Outlined'},
  {'type': 'icon', 'icon': IconData(0xf0152, fontFamily: 'MaterialIcons'), 'label': 'Sentiment Very Satisfied Rounded'},
  {'type': 'icon', 'icon': IconData(0xe5c5, fontFamily: 'MaterialIcons'), 'label': 'Smart Toy'},
  {'type': 'icon', 'icon': IconData(0xf3a8, fontFamily: 'MaterialIcons'), 'label': 'Smart Toy Outlined'},
  {'type': 'icon', 'icon': IconData(0xe5a4, fontFamily: 'MaterialIcons'), 'label': 'Sick'},
  {'type': 'icon', 'icon': IconData(0xf387, fontFamily: 'MaterialIcons'), 'label': 'Sick Outlined'},
  {'type': 'icon', 'icon': IconData(0xe621, fontFamily: 'MaterialIcons'), 'label': 'Support Agent'},
  {'type': 'icon', 'icon': IconData(0xe510, fontFamily: 'MaterialIcons'), 'label': 'Record Voice Over'},
  {'type': 'icon', 'icon': IconData(0xf0873, fontFamily: 'MaterialIcons'), 'label': 'Psychology Alt'},
  {'type': 'icon', 'icon': IconData(0xe4ef, fontFamily: 'MaterialIcons'), 'label': 'Psychology'},
  {'type': 'icon', 'icon': IconData(0xe491, fontFamily: 'MaterialIcons'), 'label': 'Person'},
  {'type': 'icon', 'icon': IconData(0xe3fe, fontFamily: 'MaterialIcons'), 'label': 'Mood'},

  //Comidas
  {'type': 'icon', 'icon': IconData(0xe3a0, fontFamily: 'MaterialIcons'), 'label': 'Pizza'},
  {'type': 'icon', 'icon': IconData(0xe538, fontFamily: 'MaterialIcons'), 'label': 'Rice Bowl'},
  {'type': 'icon', 'icon': IconData(0xe532, fontFamily: 'MaterialIcons'), 'label': 'Restaurant'},
  {'type': 'icon', 'icon': IconData(0xe533, fontFamily: 'MaterialIcons'), 'label': 'Restaurant Menu'},
  {'type': 'icon', 'icon': IconData(0xe6f1, fontFamily: 'MaterialIcons'), 'label': 'Wine Bar'},
  {'type': 'icon', 'icon': IconData(0xe644, fontFamily: 'MaterialIcons'), 'label': 'Tapas'},
  {'type': 'icon', 'icon': IconData(0xe57e, fontFamily: 'MaterialIcons'), 'label': 'Set Meal'},
  {'type': 'icon', 'icon': IconData(0xf056c, fontFamily: 'MaterialIcons'), 'label': 'Soup Kitchen'},
  {'type': 'icon', 'icon': IconData(0xe506, fontFamily: 'MaterialIcons'), 'label': 'Ramen Dining'},
  {'type': 'icon', 'icon': IconData(0xe463, fontFamily: 'MaterialIcons'), 'label': 'Outdoor Grill'},
  {'type': 'icon', 'icon': IconData(0xe42d, fontFamily: 'MaterialIcons'), 'label': 'Nightlife'},
  {'type': 'icon', 'icon': IconData(0xe383, fontFamily: 'MaterialIcons'), 'label': 'Liquor'},
  {'type': 'icon', 'icon': IconData(0xe38c, fontFamily: 'MaterialIcons'), 'label': 'Local Bar'},
  {'type': 'icon', 'icon': IconData(0xe38d, fontFamily: 'MaterialIcons'), 'label': 'Local Cafe'},
  {'type': 'icon', 'icon': IconData(0xe390, fontFamily: 'MaterialIcons'), 'label': 'Local Dining'},
  {'type': 'icon', 'icon': IconData(0xe2ca, fontFamily: 'MaterialIcons'), 'label': 'Free Breakfast'},
  {'type': 'icon', 'icon': IconData(0xe296, fontFamily: 'MaterialIcons'), 'label': 'Flatware'},
  {'type': 'icon', 'icon': IconData(0xe331, fontFamily: 'MaterialIcons'), 'label': 'Icecream'},
  {'type': 'icon', 'icon': IconData(0xf052a, fontFamily: 'MaterialIcons'), 'label': 'Kebab Dining'},
  {'type': 'icon', 'icon': IconData(0xe3c2, fontFamily: 'MaterialIcons'), 'label': 'Lunch Dining'},
  {'type': 'icon', 'icon': IconData(0xe0c9, fontFamily: 'MaterialIcons'), 'label': 'Bakery Dining'},
  {'type': 'icon', 'icon': IconData(0xe120, fontFamily: 'MaterialIcons'), 'label': 'Cake'},
  {'type': 'icon', 'icon': IconData(0xe178, fontFamily: 'MaterialIcons'), 'label': 'Coffee'},
  {'type': 'icon', 'icon': IconData(0xf04f8, fontFamily: 'MaterialIcons'), 'label': 'Egg'},
  {'type': 'icon', 'icon': IconData(0xf04f7, fontFamily: 'MaterialIcons'), 'label': 'Egg Alt'},

  //Objetos
  {'type': 'icon', 'icon': IconData(0xe2f2, fontFamily: 'MaterialIcons'), 'label': 'Handyman'},
  {'type': 'icon', 'icon': IconData(0xe2f3, fontFamily: 'MaterialIcons'), 'label': 'Hardware'},
  {'type': 'icon', 'icon': IconData(0xe2ff, fontFamily: 'MaterialIcons'), 'label': 'Headphones'},
  {'type': 'icon', 'icon': IconData(0xe304, fontFamily: 'MaterialIcons'), 'label': 'Healing'},
  {'type': 'icon', 'icon': IconData(0xe40d, fontFamily: 'MaterialIcons'), 'label': 'Movie'},
  {'type': 'icon', 'icon': IconData(0xf07b7, fontFamily: 'MaterialIcons'), 'label': 'Oil Barrel'},
  {'type': 'icon', 'icon': IconData(0xe44f, fontFamily: 'MaterialIcons'), 'label': 'Notifications'},
  {'type': 'icon', 'icon': IconData(0xe46b, fontFamily: 'MaterialIcons'), 'label': 'Palette'},
  {'type': 'icon', 'icon': IconData(0xf086f, fontFamily: 'MaterialIcons'), 'label': 'Pallet'},
  {'type': 'icon', 'icon': IconData(0xe479, fontFamily: 'MaterialIcons'), 'label': 'Party Mode'},
  {'type': 'icon', 'icon': IconData(0xe502, fontFamily: 'MaterialIcons'), 'label': 'Radio'},
  {'type': 'icon', 'icon': IconData(0xf0548, fontFamily: 'MaterialIcons'), 'label': 'Phishing'},
  {'type': 'icon', 'icon': IconData(0xe4a3, fontFamily: 'MaterialIcons'), 'label': 'Phone Android'},
  {'type': 'icon', 'icon': IconData(0xe4f4, fontFamily: 'MaterialIcons'), 'label': 'Push Pin'},
  {'type': 'icon', 'icon': IconData(0xe4ee, fontFamily: 'MaterialIcons'), 'label': 'Production Quantity Limits'},
  {'type': 'icon', 'icon': IconData(0xf07b9, fontFamily: 'MaterialIcons'), 'label': 'Propane'},
  {'type': 'icon', 'icon': IconData(0xf07ba, fontFamily: 'MaterialIcons'), 'label': 'Propane Tank'},
  {'type': 'icon', 'icon': IconData(0xe4ea, fontFamily: 'MaterialIcons'), 'label': 'Print'},
  {'type': 'icon', 'icon': IconData(0xe4e0, fontFamily: 'MaterialIcons'), 'label': 'Power'},
  {'type': 'icon', 'icon': IconData(0xe4e4, fontFamily: 'MaterialIcons'), 'label': 'Precision Manufacturing'},
  {'type': 'icon', 'icon': IconData(0xe4d5, fontFamily: 'MaterialIcons'), 'label': 'Plumbing'},
  {'type': 'icon', 'icon': IconData(0xe4d8, fontFamily: 'MaterialIcons'), 'label': 'Point Of Sale'},
  {'type': 'icon', 'icon': IconData(0xe511, fontFamily: 'MaterialIcons'), 'label': 'Redeem'},
  {'type': 'icon', 'icon': IconData(0xe50c, fontFamily: 'MaterialIcons'), 'label': 'Receipt'},
  {'type': 'icon', 'icon': IconData(0xf0564, fontFamily: 'MaterialIcons'), 'label': 'Scale'},
  {'type': 'icon', 'icon': IconData(0xe554, fontFamily: 'MaterialIcons'), 'label': 'Scanner'},
  {'type': 'icon', 'icon': IconData(0xf0562, fontFamily: 'MaterialIcons'), 'label': 'Satellite Alt'},
  {'type': 'icon', 'icon': IconData(0xe550, fontFamily: 'MaterialIcons'), 'label': 'Save'},
  {'type': 'icon', 'icon': IconData(0xe553, fontFamily: 'MaterialIcons'), 'label': 'Savings'},
  {'type': 'icon', 'icon': IconData(0xe54e, fontFamily: 'MaterialIcons'), 'label': 'Sanitizer'},
  {'type': 'icon', 'icon': IconData(0xe53d, fontFamily: 'MaterialIcons'), 'label': 'Room Service'},
  {'type': 'icon', 'icon': IconData(0xe542, fontFamily: 'MaterialIcons'), 'label': 'Router'},
  {'type': 'icon', 'icon': IconData(0xf06c0, fontFamily: 'MaterialIcons'), 'label': 'Roller Skating'},
  {'type': 'icon', 'icon': IconData(0xe5db, fontFamily: 'MaterialIcons'), 'label': 'Speaker'},
  {'type': 'icon', 'icon': IconData(0xe59b, fontFamily: 'MaterialIcons'), 'label': 'Shopping Basket'},
  {'type': 'icon', 'icon': IconData(0xe59c, fontFamily: 'MaterialIcons'), 'label': 'Shopping Cart'},
  {'type': 'icon', 'icon': IconData(0xe5a0, fontFamily: 'MaterialIcons'), 'label': 'Shower'},
  {'type': 'icon', 'icon': IconData(0xe59a, fontFamily: 'MaterialIcons'), 'label': 'Shopping Bag'},
  {'type': 'icon', 'icon': IconData(0xe58a, fontFamily: 'MaterialIcons'), 'label': 'Settings Input Hdmi'},
  {'type': 'icon', 'icon': IconData(0xe574, fontFamily: 'MaterialIcons'), 'label': 'Sensor Door'},
  {'type': 'icon', 'icon': IconData(0xe564, fontFamily: 'MaterialIcons'), 'label': 'Sd Card'},
  {'type': 'icon', 'icon': IconData(0xe567, fontFamily: 'MaterialIcons'), 'label': 'Search'},
  {'type': 'icon', 'icon': IconData(0xe559, fontFamily: 'MaterialIcons'), 'label': 'School'},
  {'type': 'icon', 'icon': IconData(0xe55a, fontFamily: 'MaterialIcons'), 'label': 'Science'},
  {'type': 'icon', 'icon': IconData(0xe656, fontFamily: 'MaterialIcons'), 'label': 'Thermostat'},
  {'type': 'icon', 'icon': IconData(0xe655, fontFamily: 'MaterialIcons'), 'label': 'Theaters'},
  {'type': 'icon', 'icon': IconData(0xf0585, fontFamily: 'MaterialIcons'), 'label': 'Table Restaurant'},
  {'type': 'icon', 'icon': IconData(0xf0584, fontFamily: 'MaterialIcons'), 'label': 'Table Bar'},
  {'type': 'icon', 'icon': IconData(0xf0597, fontFamily: 'MaterialIcons'), 'label': 'Vaccines'},
  {'type': 'icon', 'icon': IconData(0xe68a, fontFamily: 'MaterialIcons'), 'label': 'Umbrella'},
  {'type': 'icon', 'icon': IconData(0xf0878, fontFamily: 'MaterialIcons'), 'label': 'Trolley'},
  {'type': 'icon', 'icon': IconData(0xe671, fontFamily: 'MaterialIcons'), 'label': 'Tour'},
  {'type': 'icon', 'icon': IconData(0xf06c4, fontFamily: 'MaterialIcons'), 'label': 'Tire Repair'},
  {'type': 'icon', 'icon': IconData(0xe662, fontFamily: 'MaterialIcons'), 'label': 'Timer'},
  {'type': 'icon', 'icon': IconData(0xe6f2, fontFamily: 'MaterialIcons'), 'label': 'Work'},
  {'type': 'icon', 'icon': IconData(0xf07da, fontFamily: 'MaterialIcons'), 'label': 'Wind Power'},
  {'type': 'icon', 'icon': IconData(0xe6e1, fontFamily: 'MaterialIcons'), 'label': 'Weekend'},
  {'type': 'icon', 'icon': IconData(0xe6ce, fontFamily: 'MaterialIcons'), 'label': 'Watch'},
  {'type': 'icon', 'icon': IconData(0xf07d4, fontFamily: 'MaterialIcons'), 'label': 'Wallet'},
  {'type': 'icon', 'icon': IconData(0xe6c7, fontFamily: 'MaterialIcons'), 'label': 'Vpn Key'},
  {'type': 'icon', 'icon': IconData(0xe2d3, fontFamily: 'MaterialIcons'), 'label': 'Gavel'},
  {'type': 'icon', 'icon': IconData(0xe2bb, fontFamily: 'MaterialIcons'), 'label': 'Format Paint'},
  {'type': 'icon', 'icon': IconData(0xf76f, fontFamily: 'MaterialIcons'), 'label': 'Flashlight On Rounded'},
  {'type': 'icon', 'icon': IconData(0xe326, fontFamily: 'MaterialIcons'), 'label': 'Hourglass Full'},
  {'type': 'icon', 'icon': IconData(0xe28e, fontFamily: 'MaterialIcons'), 'label': 'Flag'},
  {'type': 'icon', 'icon': IconData(0xe32e, fontFamily: 'MaterialIcons'), 'label': 'Https'},
  {'type': 'icon', 'icon': IconData(0xe330, fontFamily: 'MaterialIcons'), 'label': 'Ice Skating'},
  {'type': 'icon', 'icon': IconData(0xe39a, fontFamily: 'MaterialIcons'), 'label': 'Local Mall'},
  {'type': 'icon', 'icon': IconData(0xe39b, fontFamily: 'MaterialIcons'), 'label': 'Local Movies'},
  {'type': 'icon', 'icon': IconData(0xe39c, fontFamily: 'MaterialIcons'), 'label': 'Local Offer'},
  {'type': 'icon', 'icon': IconData(0xe397, fontFamily: 'MaterialIcons'), 'label': 'Local Hotel'},
  {'type': 'icon', 'icon': IconData(0xe398, fontFamily: 'MaterialIcons'), 'label': 'Local Laundry Service'},
  {'type': 'icon', 'icon': IconData(0xe394, fontFamily: 'MaterialIcons'), 'label': 'Local Gas Station'},
  {'type': 'icon', 'icon': IconData(0xe395, fontFamily: 'MaterialIcons'), 'label': 'Local Grocery Store'},
  {'type': 'icon', 'icon': IconData(0xf052b, fontFamily: 'MaterialIcons'), 'label': 'Key'},
  {'type': 'icon', 'icon': IconData(0xe35c, fontFamily: 'MaterialIcons'), 'label': 'Keyboard Voice'},
  {'type': 'icon', 'icon': IconData(0xe3ae, fontFamily: 'MaterialIcons'), 'label': 'Lock'},
  {'type': 'icon', 'icon': IconData(0xe3c1, fontFamily: 'MaterialIcons'), 'label': 'Luggage'},
  {'type': 'icon', 'icon': IconData(0xe3a3, fontFamily: 'MaterialIcons'), 'label': 'Local Post Office'},
  {'type': 'icon', 'icon': IconData(0xe3a4, fontFamily: 'MaterialIcons'), 'label': 'Local Print Shop'},
  {'type': 'icon', 'icon': IconData(0xe3a5, fontFamily: 'MaterialIcons'), 'label': 'Local See'},
  {'type': 'icon', 'icon': IconData(0xe40b, fontFamily: 'MaterialIcons'), 'label': 'Mouse'},
  {'type': 'icon', 'icon': IconData(0xe40d, fontFamily: 'MaterialIcons'), 'label': 'Movie'},
  {'type': 'icon', 'icon': IconData(0xe084, fontFamily: 'MaterialIcons'), 'label': 'Anchor'},
  {'type': 'icon', 'icon': IconData(0xe3d3, fontFamily: 'MaterialIcons'), 'label': 'Masks'},
  {'type': 'icon', 'icon': IconData(0xe3d8, fontFamily: 'MaterialIcons'), 'label': 'Medical Services'},
  {'type': 'icon', 'icon': IconData(0xe3d9, fontFamily: 'MaterialIcons'), 'label': 'Medication'},
  {'type': 'icon', 'icon': IconData(0xe3e1, fontFamily: 'MaterialIcons'), 'label': 'Mic'},
  {'type': 'icon', 'icon': IconData(0xe3e7, fontFamily: 'MaterialIcons'), 'label': 'Military Tech'},
  {'type': 'icon', 'icon': IconData(0xe3e9, fontFamily: 'MaterialIcons'), 'label': 'Miscellaneous Services'},
  {'type': 'icon', 'icon': IconData(0xe0bb, fontFamily: 'MaterialIcons'), 'label': 'Auto Fix High'},
  {'type': 'icon', 'icon': IconData(0xe0ae, fontFamily: 'MaterialIcons'), 'label': 'Assistant Photo'},
  {'type': 'icon', 'icon': IconData(0xe0b1, fontFamily: 'MaterialIcons'), 'label': 'Attach File'},
  {'type': 'icon', 'icon': IconData(0xe090, fontFamily: 'MaterialIcons'), 'label': 'Architecture'},
  {'type': 'icon', 'icon': IconData(0xe0a6, fontFamily: 'MaterialIcons'), 'label': 'Assignment Ind'},
  {'type': 'icon', 'icon': IconData(0xe0e0, fontFamily: 'MaterialIcons'), 'label': 'Blender'},
  {'type': 'icon', 'icon': IconData(0xe0d2, fontFamily: 'MaterialIcons'), 'label': 'Battery Full'},
  {'type': 'icon', 'icon': IconData(0xe0d6, fontFamily: 'MaterialIcons'), 'label': 'Beach Access'},
  {'type': 'icon', 'icon': IconData(0xe0d7, fontFamily: 'MaterialIcons'), 'label': 'Bed'},
  {'type': 'icon', 'icon': IconData(0xf04c6, fontFamily: 'MaterialIcons'), 'label': 'Balance'},
  {'type': 'icon', 'icon': IconData(0xe0c8, fontFamily: 'MaterialIcons'), 'label': 'Badge'},
  {'type': 'icon', 'icon': IconData(0xe141, fontFamily: 'MaterialIcons'), 'label': 'Carpenter'},
  {'type': 'icon', 'icon': IconData(0xe142, fontFamily: 'MaterialIcons'), 'label': 'Cases'},
  {'type': 'icon', 'icon': IconData(0xe143, fontFamily: 'MaterialIcons'), 'label': 'Casino'},
  {'type': 'icon', 'icon': IconData(0xe138, fontFamily: 'MaterialIcons'), 'label': 'Campaign'},
  {'type': 'icon', 'icon': IconData(0xe126, fontFamily: 'MaterialIcons'), 'label': 'Call'},
  {'type': 'icon', 'icon': IconData(0xe130, fontFamily: 'MaterialIcons'), 'label': 'Camera Alt'},
  {'type': 'icon', 'icon': IconData(0xe11c, fontFamily: 'MaterialIcons'), 'label': 'Business Center'},
  {'type': 'icon', 'icon': IconData(0xe11e, fontFamily: 'MaterialIcons'), 'label': 'Cable'},
  {'type': 'icon', 'icon': IconData(0xe116, fontFamily: 'MaterialIcons'), 'label': 'Build'},
  {'type': 'icon', 'icon': IconData(0xe113, fontFamily: 'MaterialIcons'), 'label': 'Brush'},
  {'type': 'icon', 'icon': IconData(0xe17c, fontFamily: 'MaterialIcons'), 'label': 'Color Lens'},
  {'type': 'icon', 'icon': IconData(0xe189, fontFamily: 'MaterialIcons'), 'label': 'Construction'},
  {'type': 'icon', 'icon': IconData(0xe1a2, fontFamily: 'MaterialIcons'), 'label': 'Crib'},
  {'type': 'icon', 'icon': IconData(0xe149, fontFamily: 'MaterialIcons'), 'label': 'Celebration'},
  {'type': 'icon', 'icon': IconData(0xf04cc, fontFamily: 'MaterialIcons'), 'label': 'Cell Tower'},
  {'type': 'icon', 'icon': IconData(0xe14d, fontFamily: 'MaterialIcons'), 'label': 'Chair'},
  {'type': 'icon', 'icon': IconData(0xe84b, fontFamily: 'MaterialIcons'), 'label': 'Chair Sharp'},
  {'type': 'icon', 'icon': IconData(0xe15d, fontFamily: 'MaterialIcons'), 'label': 'Checkroom'},
  {'type': 'icon', 'icon': IconData(0xe161, fontFamily: 'MaterialIcons'), 'label': 'Child Friendly'},
  {'type': 'icon', 'icon': IconData(0xef80, fontFamily: 'MaterialIcons'), 'label': 'Cut Outlined'},
  {'type': 'icon', 'icon': IconData(0xf079a, fontFamily: 'MaterialIcons'), 'label': 'Desk'},
  {'type': 'icon', 'icon': IconData(0xe1c2, fontFamily: 'MaterialIcons'), 'label': 'Desktop Mac'},
  {'type': 'icon', 'icon': IconData(0xe1c9, fontFamily: 'MaterialIcons'), 'label': 'Device Thermostat'},
  {'type': 'icon', 'icon': IconData(0xf04ed, fontFamily: 'MaterialIcons'), 'label': 'Diamond'},
  {'type': 'icon', 'icon': IconData(0xe1b7, fontFamily: 'MaterialIcons'), 'label': 'Deck'},
  {'type': 'icon', 'icon': IconData(0xe1b9, fontFamily: 'MaterialIcons'), 'label': 'Delete'},
  {'type': 'icon', 'icon': IconData(0xe20e, fontFamily: 'MaterialIcons'), 'label': 'Dry Cleaning'},
  {'type': 'icon', 'icon': IconData(0xe28d, fontFamily: 'MaterialIcons'), 'label': 'Fitness Center'},
  {'type': 'icon', 'icon': IconData(0xe8f9, fontFamily: 'MaterialIcons'), 'label': 'Door Front Door Sharp'},
  {'type': 'icon', 'icon': IconData(0xe242, fontFamily: 'MaterialIcons'), 'label': 'Event Seat'},
  {'type': 'icon', 'icon': IconData(0xe250, fontFamily: 'MaterialIcons'), 'label': 'Extension'},
  {'type': 'icon', 'icon': IconData(0xe22a, fontFamily: 'MaterialIcons'), 'label': 'Email'},
  {'type': 'icon', 'icon': IconData(0xe22c, fontFamily: 'MaterialIcons'), 'label': 'Emoji Events'},

  //Objeto & Marca
  {'type': 'icon', 'icon': IconData(0xe4db, fontFamily: 'MaterialIcons'), 'label': 'Polymer'},

  //Marcas
  {'type': 'icon', 'icon': IconData(0xf04be, fontFamily: 'MaterialIcons'), 'label': 'Apple'},
  {'type': 'icon', 'icon': IconData(0xf0567, fontFamily: 'MaterialIcons'), 'label': 'Shopify'},
  {'type': 'icon', 'icon': IconData(0xf056a, fontFamily: 'MaterialIcons'), 'label': 'Snapchat'},
  {'type': 'icon', 'icon': IconData(0xf058c, fontFamily: 'MaterialIcons'), 'label': 'Tiktok'},

];

final List<Map<String, dynamic>> stampBackgroundIconsMap = [

  {'type': 'icon', 'icon': IconData(0xe163, fontFamily: 'MaterialIcons'), 'label': 'Círculo'},
  {'type': 'icon', 'icon': IconData(0xf0570, fontFamily: 'MaterialIcons'), 'label': 'Quadrado'},
  {'type': 'icon', 'icon': IconData(0xf0385, fontFamily: 'MaterialIcons'), 'label': 'Quadrado Arredondado'},
  {'type': 'icon', 'icon': IconData(0xf0546, fontFamily: 'MaterialIcons'), 'label': 'Pentágono'},
  {'type': 'icon', 'icon': IconData(0xf0517, fontFamily: 'MaterialIcons'), 'label': 'Hexágono'},
  {'type': 'icon', 'icon': IconData(0xe25b, fontFamily: 'MaterialIcons'), 'label': 'Coração'},
  {'type': 'icon', 'icon': IconData(0xe596, fontFamily: 'MaterialIcons'), 'label': 'Escudo'},
  {'type': 'icon', 'icon': IconData(0xe0f1, fontFamily: 'MaterialIcons'), 'label': 'Marcador'},
  {'type': 'icon', 'icon': IconData(0xe5f9, fontFamily: 'MaterialIcons'), 'label': 'Estrela'},
  //{'type': 'icon', 'icon': IconData(0xf07b5, fontFamily: 'MaterialIcons'), 'label': 'Noise Aware'},
  {'type': 'icon', 'icon': IconData(0xf0518, fontFamily: 'MaterialIcons'), 'label': 'Hive'},
  {'type': 'icon', 'icon': IconData(0xe109, fontFamily: 'MaterialIcons'), 'label': 'Brightness 5'},

];