// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-imcwiIvO77AwytJ0iDE0ZJK6GCmbRCQ',
    appId: '1:905559298087:web:33fc79e812df8e50073e02',
    messagingSenderId: '905559298087',
    projectId: 'giftychain-giftelo-cardapp',
    authDomain: 'giftychain-giftelo-cardapp.firebaseapp.com',
    storageBucket: 'giftychain-giftelo-cardapp.firebasestorage.app',
    measurementId: 'G-4W49D2C8RJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfYyb8KY_ZTYRB7S0npMDKsUsbo0K7iX0',
    appId: '1:905559298087:android:a400d87ad6c981aa073e02',
    messagingSenderId: '905559298087',
    projectId: 'giftychain-giftelo-cardapp',
    storageBucket: 'giftychain-giftelo-cardapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANwrE4Dvx_eKpfBYIHCy92RmEba0pdQyo',
    appId: '1:905559298087:ios:b6e6c7664c80ab69073e02',
    messagingSenderId: '905559298087',
    projectId: 'giftychain-giftelo-cardapp',
    storageBucket: 'giftychain-giftelo-cardapp.firebasestorage.app',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANwrE4Dvx_eKpfBYIHCy92RmEba0pdQyo',
    appId: '1:905559298087:ios:b6e6c7664c80ab69073e02',
    messagingSenderId: '905559298087',
    projectId: 'giftychain-giftelo-cardapp',
    storageBucket: 'giftychain-giftelo-cardapp.firebasestorage.app',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-imcwiIvO77AwytJ0iDE0ZJK6GCmbRCQ',
    appId: '1:905559298087:web:63feb3dda65a6458073e02',
    messagingSenderId: '905559298087',
    projectId: 'giftychain-giftelo-cardapp',
    authDomain: 'giftychain-giftelo-cardapp.firebaseapp.com',
    storageBucket: 'giftychain-giftelo-cardapp.firebasestorage.app',
    measurementId: 'G-C52W11N5X3',
  );

}